### PR TITLE
Allow PSR-0 and PSR-4 compliant bundles

### PR DESCRIPTION
**Pull request by wysow**
|Q            |A   |
|---          |--- |
|Bug Fix?     |n   |
|New Feature? |y   |
|BC Breaks?   |n   |
|Deprecations?|n   |
|Tests Pass?  |y   |
|Fixed Tickets|#433|
|License      |-   |
|Doc PR       |    |
                    

This is a functional WIP, comments are very welcome

### CODE REVIEW

**Comment by robcaw** [comment]
Is this still WIP? What's the status of this PR?

**Comment by docteurklein** [comment]
ping @wysow

**Comment by wysow** [comment]
This PR is waiting for code review and maybe other ideas to optimize the detection mechanism...

**Comment by docteurklein** [comment]
i think it has been reviewed enough. Let's improve in another PR if needed.

I'm personally  +1 to merge it if you think it's ready.

**Pull request merged**
