### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by wysow**
|Q            |A   |
|---          |--- |
|Bug Fix?     |n   |
|New Feature? |n   |
|BC Breaks?   |n   |
|Deprecations?|n   |
|Tests Pass?  |y   |
|Fixed Tickets|#429|
|License      |-   |
|Doc PR       |    |
                    

 Based on @pzaloznyi work

### CODE REVIEW

**Comment by wysow** [comment]
@pzaloznyi Does this seems ok for you or did I missed something??

**Comment by pzaloznyi** [comment]
@wysow ok from my side :)

**Comment by docteurklein** [comment]
same as @pilot , there is no bug fix, just typo

**Comment by wysow** [comment]
sure @pilot and @docteurklein you're right, no bug fix but typo in here, my bad... I'm going to rebase it so it can be merged

**Comment by docteurklein** [comment]
commit message is misleading

**Comment by stof** [comment]
Github tells me there is a merge conflict

**Comment by docteurklein** [comment]
more importantly, are you sure https://github.com/KnpLabs/KnpBundles/pull/429 fixes are merged? 
The actual fix is more important than tne typo.

**Comment by wysow** [comment]
@docteurklein seems they are as seen here https://github.com/KnpLabs/KnpBundles/blob/master/src/Knp/Bundle/KnpBundlesBundle/Github/Repo.php#L265-271

**Comment by docteurklein** [comment]
@wysow ok cool thanks for looking

**Comment by docteurklein** [comment]
lol are we discussing for 8 months about an carriage return?!

**Pull request closed without merging**
